polarismesh/polaris-java

polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/plugin/PluginConfigImpl.java

fix:fix circuitbreaker plugin not found bug when doesn't use circuitbreaker

fix:fix circuitbreaker plugin not found bug

---

polaris-common/polaris-protobuf/pom.xml

delete `pluginId` and add `protoSourceRoot`  config , optimize code comments   
in `polaris-java/polaris-common/polaris-protobuf/pom.xml`

add protoSourceRoot config for protobuf-maven-plugin, optimize polaris-protobuf/pom.xml code comments

---

polaris-dependencies/pom.xml
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/GrpcConnector.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/ServiceUpdateTask.java
pom.xml

fix the log flush issue

---

polaris-distribution/polaris-all/pom.xml
pom.xml

fix: polaris-all reference error, showing revision not found

---

polaris-examples/quickstart-example/quickstart-example-consumer/src/main/docker/Dockerfile
polaris-examples/quickstart-example/quickstart-example-consumer/src/main/resources/polaris.yml
polaris-examples/quickstart-example/quickstart-example-provider/src/main/docker/Dockerfile
polaris-examples/quickstart-example/quickstart-example-provider/src/main/resources/polaris.yml
polaris-plugins/polaris-plugins-router/router-rule/src/main/java/com/tencent/polaris/plugins/router/rule/RuleBasedRouter.java

feat:  add dockerfile to quickstart examples

fix #43: 规则路由单实例list不支持写入数据

---

polaris-common/polaris-client/src/main/java/com/tencent/polaris/client/flow/BaseFlow.java
polaris-common/polaris-client/src/main/java/com/tencent/polaris/client/flow/GetResourcesInvoker.java
polaris-common/polaris-client/src/main/java/com/tencent/polaris/client/flow/ResourcesResponse.java
polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/pojo/ServiceEventKey.java
polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/pojo/ServiceInfo.java
polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/pojo/Services.java
polaris-common/polaris-model/src/main/java/com/tencent/polaris/client/pojo/ServicesByProto.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/core/ConsumerAPI.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/GetServicesRequest.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/ServicesResponse.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultConsumerAPI.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/CommonServicesRequest.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/SyncFlow.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/util/Validator.java
polaris-discovery/polaris-discovery-factory/src/test/java/com/tencent/polaris/discovery/test/core/GetServicesTest.java
polaris-examples/discovery-example/src/main/java/com/tencent/polaris/discovery/example/consumer/GetAllInstancesExample.java
polaris-examples/discovery-example/src/main/java/com/tencent/polaris/discovery/example/consumer/GetOneInstanceExample.java
polaris-examples/discovery-example/src/main/java/com/tencent/polaris/discovery/example/consumer/GetServicesExample.java
polaris-examples/discovery-example/src/main/java/com/tencent/polaris/discovery/example/utils/ExampleUtils.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/registry/LocalRegistry.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/GrpcUtil.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/SpecStreamClient.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/codec/ServicesCacheHandler.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/resources/META-INF/services/com.tencent.polaris.api.plugin.registry.CacheHandler
polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java
polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/InMemoryRegistry.java
polaris-test/polaris-test-mock-discovery/src/main/java/com/tencent/polaris/test/mock/discovery/NamingService.java

[ISSUE #50] support get service list by ConsumerAPI

---

polaris-factory/src/main/java/com/tencent/polaris/factory/api/APIFacade.java
polaris-plugins/polaris-plugins-router/router-rule/src/main/java/com/tencent/polaris/plugins/router/rule/RuleBasedRouter.java

feat: 规则路由匹配不通过则全放通

---

polaris-factory/src/main/java/com/tencent/polaris/factory/api/APIFacade.java

PolarisFacade support initContext by configuration object

---

polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/pojo/ServiceChangeEvent.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/core/ConsumerAPI.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/UnWatchServiceRequest.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/WatchServiceResponse.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultConsumerAPI.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/CommonUnWatchServiceRequest.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/util/Validator.java

[ISSUE #76] 优化service-watch

---

polaris-plugins/polaris-plugins-router/router-rule/src/main/java/com/tencent/polaris/plugins/router/rule/RuleBasedRouter.java
polaris-plugins/polaris-plugins-router/router-rule/src/test/java/com/tencent/polaris/plugins/router/rule/test/RuleBasedRouterTest.java
polaris-plugins/polaris-plugins-router/router-rule/src/test/resources/route-rules/isolated-rule.json

fix：路由规则隔离不生效问题

---

polaris-plugins/polaris-plugins-connector/connector-consul/src/main/java/com/tencent/polaris/plugins/connector/consul/ConsulAPIConnector.java
pom.xml

Fix bug causing by using consul with host with scheme such as "http://localhost".

fix:fix consul host with scheme bug.

---

polaris-distribution/polaris-all/pom.xml

[ISSUE #125]: refactor shade config

---

polaris-common/polaris-model/src/main/java/com/tencent/polaris/client/pojo/ServiceInstancesByProto.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/server/EventHandler.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/server/ServerEvent.java
polaris-plugins/polaris-plugins-connector/connector-composite/src/main/java/com/tencent/polaris/plugins/connector/composite/CompositeServiceUpdateTask.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/SpecStreamClient.java
polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/CacheObject.java

在discover请求中传递revision以实现nochange逻辑

---

polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/ConfigAPIFactory.java
polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java

feat: add create api by addresses

---

.github/workflows/testing.yml
polaris-common/polaris-logging/pom.xml
polaris-common/polaris-logging/src/main/java/com/tencent/polaris/logging/LoggerFactory.java
polaris-common/polaris-logging/src/main/java/com/tencent/polaris/logging/LoggingConsts.java
polaris-common/polaris-logging/src/main/resources/polaris-log4j.xml
polaris-common/polaris-logging/src/main/resources/polaris-log4j2.xml
polaris-common/polaris-logging/src/main/resources/polaris-logback.xml
polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/pojo/DetectResult.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultConsumerAPI.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java
polaris-examples/configuration-example/pom.xml
polaris-examples/quickstart-example/pom.xml
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/SpecStreamClient.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/test/java/com/tencent/polaris/plugins/connector/grpc/ChannelTlsCertificatesTest.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/test/java/com/tencent/polaris/plugins/connector/grpc/ManagedChannelUtilTest.java
pom.xml

feat:add some logs.

---

polaris-common/polaris-config-default/src/main/resources/conf/default-config.yml
polaris-examples/circuitbreaker-example/circuitbreaker-instance-example/circuitbreaker-instance-consumer/src/main/resources/polaris.yml
polaris-examples/circuitbreaker-example/circuitbreaker-instance-example/circuitbreaker-instance-provider/src/main/resources/polaris.yml
polaris-examples/configuration-example/src/main/resources/polaris.yml
polaris-examples/discovery-example/src/main/resources/polaris.yml
polaris-examples/quickstart-example/quickstart-example-consumer/src/main/resources/polaris.yml
polaris-examples/quickstart-example/quickstart-example-provider/src/main/resources/polaris.yml
polaris-examples/ratelimit-example/global-limiter-example/ratelimit-remote-consumer/src/main/resources/polaris.yml
polaris-examples/ratelimit-example/global-limiter-example/ratelimit-remote-provider/src/main/resources/polaris.yml
polaris-examples/ratelimit-example/local-limiter-example/ratelimit-local-consumer/src/main/resources/polaris.yml
polaris-examples/ratelimit-example/local-limiter-example/ratelimit-local-provider/src/main/resources/polaris.yml
polaris-examples/router-example/router-multienv-example/router-multienv-gateway/src/main/resources/polaris.yml
polaris-examples/router-example/router-multienv-example/router-multienv-provider/src/main/resources/polaris.yml
polaris-examples/router-example/router-version-example/router-version-consumer/src/main/resources/polaris.yml
polaris-examples/router-example/router-version-example/router-version-provider/src/main/resources/polaris.yml
polaris-plugins/polaris-plugins-observability/stat-prometheus/src/main/java/com/tencent/polaris/plugins/stat/prometheus/handler/HttpMetricHandler.java
polaris-plugins/polaris-plugins-observability/stat-prometheus/src/test/java/com/tencent/polaris/plugins/stat/prometheus/handler/PrometheusHttpServerTest.java

docs:update example for pulling of prometheus.

---

polaris-common/polaris-model/src/main/java/com/tencent/polaris/client/util/Utils.java

feat: can use [user.dir] when set persistDirPath
---------------------------------------------------
add $USER_DIR  in Utils.translatePath
$USER_DIR is mapping to System.getProperty("user.dir")

feat: can use [user.dir] when set persistDirPath

---

polaris-plugins/polaris-plugins-router/router-rule/src/main/java/com/tencent/polaris/plugins/router/rule/MatchFunctions.java
polaris-plugins/polaris-plugins-router/router-rule/src/main/java/com/tencent/polaris/plugins/router/rule/RuleBasedRouter.java
polaris-plugins/polaris-plugins-router/router-rule/src/test/java/com/tencent/polaris/plugins/router/rule/RuleBasedRouterTest.java
polaris-plugins/polaris-plugins-router/router-rule/src/test/resources/route-rules/match-function-in-rule.json
polaris-plugins/polaris-plugins-router/router-rule/src/test/resources/route-rules/match-function-not_equals-rule.json
polaris-plugins/polaris-plugins-router/router-rule/src/test/resources/route-rules/match-function-not_in-rule.json
polaris-plugins/polaris-plugins-router/router-rule/src/test/resources/route-rules/match-function-regx-rule.json

#196 
- 路由规则计算支持 正则、等于、不等于、包含、不包含

[ISSUE #196] 路由规则支持多计算规则

---

polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/WatchFlow.java

Refactor: Trigger the listener added for the first time

---

polaris-common/polaris-config/src/main/java/com/tencent/polaris/api/config/consumer/CircuitBreakerConfig.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/consumer/CircuitBreakerConfigImpl.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-common/src/main/java/com/tencent/polaris/plugins/circuitbreaker/common/CircuitBreakUtils.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-errcount/src/main/java/com/tencent/polaris/plugins/circuitbreaker/errcount/ConsecutiveCircuitBreaker.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-errrate/src/main/java/com/tencent/polaris/plugins/circuitbreaker/errrate/ErrRateCircuitBreaker.java

熔断规则远程拉取添加开关，当不拉取远程规则时，取默认规则（空）。

feature: 熔断规则远程拉取添加开关。

---

polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/SpecStreamClient.java

fix:discover请求只判断stream状态导致无法定时切换服务器的问题

---

polaris-common/polaris-protobuf/pom.xml
polaris-examples/location-example/pom.xml
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/test/java/com/tencent/polaris/plugins/connector/grpc/ManagedChannelUtilTest.java
polaris-plugins/polaris-plugins-location/location-provider-remotehttp/pom.xml
pom.xml

Upgrade protobuf-java to 3.21.7

---

polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/GetHealthyInstancesRequest.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/CommonInstancesRequest.java
polaris-distribution/polaris-all/pom.xml
polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/InMemoryRegistry.java
polaris-plugins/polaris-plugins-router/router-healthy/src/main/java/com/tencent/polaris/plugins/router/healthy/RecoverRouter.java
pom.xml

fix: 
- okio jar包冲突问题
- healthyInstances返回熔断实例问题
- 熔断状态变更无法触发watch的问题

合入BUGFIX变更

---

polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/plugin/PluginConfigImpl.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/util/ConfigUtils.java

refactor: 插件配置类支持缓存

---

.github/workflows/release.yml
.github/workflows/snapshot.yml
.github/workflows/testing.yml
polaris-common/polaris-client/src/main/java/com/tencent/polaris/client/flow/BaseFlow.java
polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/pojo/ServiceEventKey.java
polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/utils/StringUtils.java
polaris-common/polaris-model/src/test/java/com/tencent/polaris/api/pojo/ServiceEventKeyTest.java
polaris-plugins/polaris-plugins-configuration-connector/polaris-configuration-connector/src/main/java/com/tencent/polaris/plugins/configuration/connector/polaris/PolarisConfigFileConnector.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/Connection.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/ConnectionManager.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/GrpcConnector.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/SpecStreamClient.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/test/java/com/tencent/polaris/plugins/connector/grpc/ConnectionManagerTest.java
pom.xml

[ISSUE #276] refactor:not switch on fail when only one address

---

polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/InstancesResponse.java

fix break change for SCT compile error

fix: fix break change for SCT

---

polaris-plugins/polaris-plugins-connector/connector-consul/pom.xml
polaris-plugins/polaris-plugins-connector/connector-nacos/pom.xml
pom.xml

[ISSUE #152] update dependencies

---

polaris-configuration/polaris-configuration-client/src/main/java/com/tencent/polaris/configuration/client/internal/ConfigPropertiesFile.java

[ISSUE #260] remove getting system property when use ConfigPropertiesFile#getProperty

---

polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java

quickstart/provider examples 添加注释，标明实例id不是必填

---

polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/InstancesResponse.java
pom.xml

- fix break change
- update version

fix: fix break change

---

polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/RegisterFlow.java
polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java

fix heartbeat with instance id

---

polaris-common/polaris-client/src/main/java/com/tencent/polaris/client/api/SDKContext.java

issue [#275](https://github.com/polarismesh/polaris-java/issues/275) print SDKContext Configuration

issue #275 print SDKContext Configuration

---

polaris-examples/discovery-example/src/main/java/com/tencent/polaris/discovery/example/consumer/GetInstancesExample.java
polaris-examples/discovery-example/src/main/resources/polaris.yml
polaris-examples/ratelimit-example/local-limiter-example/ratelimit-local-consumer/src/main/java/com/tencent/polaris/ratelimit/local/example/Consumer.java
polaris-plugins/polaris-plugins-healthchecker/healthchecker-http/src/test/java/com/tencent/polaris/plugins/outlier/detector/http/HttpHealthCheckerTest.java
polaris-plugins/polaris-plugins-ratelimiter/ratelimiter-unirate/src/main/java/com/tencent/polaris/plugins/ratelimiter/unirate/RemoteAwareLeakyBucket.java
polaris-plugins/polaris-plugins-router/router-nearby/src/main/java/com/tencent/polaris/plugins/router/nearby/NearbyRouter.java

fix:修复匀速排队限流以及就近路由无法通过ConsumerAPI生效

---

polaris-examples/quickstart-example/quickstart-example-provider/src/main/java/com/tencent/polaris/quickstart/example/Provider.java

修改provider demo，启动多个provider时，指定注册实例id需要保证唯一

---

polaris-circuitbreaker/polaris-circuitbreaker-client/src/main/java/com/tencent/polaris/circuitbreak/client/task/InstancesDetectTask.java

bugfix：区分插件的探测结果与最终返回结果。解决在配置多个探测插件情况下，一个组件探测失败，一个组件无结果，导致无最终探测结果的情况

---

polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/CircuitBreakerRuleContainer.java
polaris-plugins/polaris-plugins-location/location-provider-remotehttp/pom.xml
polaris-plugins/polaris-plugins-location/location-provider-remotehttp/src/main/java/com/tencent/polaris/plugin/location/remotehttp/RemoteHttpLocationProvider.java

- fix: check if FaultDetect is enabled in CircuitBreaker
- cherry pick https://github.com/polarismesh/polaris-java/commit/4152b461226549e1b0fb75e949659ddde6e4fe0a

fix: check if FaultDetect is enabled in CircuitBreaker

---

polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/MatchUtils.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/ResourceHealthChecker.java

fix sortFaultDetectRules, method FaultDetectRules before service FaultDetectRules when it's method resource

fix sortFaultDetectRules

---

.github/workflows/testing.yml
pom.xml

issue https://github.com/polarismesh/polaris-java/issues/288

Add support for codecov

---

polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/GrpcConnector.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/GrpcUtil.java
polaris-ratelimit/polaris-ratelimit-client/src/main/java/com/tencent/polaris/ratelimit/client/api/DefaultLimitAPI.java
polaris-ratelimit/polaris-ratelimit-client/src/main/java/com/tencent/polaris/ratelimit/client/flow/QuotaFlow.java
polaris-ratelimit/polaris-ratelimit-client/src/main/java/com/tencent/polaris/ratelimit/client/utils/RateLimitConstants.java
pom.xml

https://github.com/polarismesh/polaris-java/issues/338

解决grpc连接报错问题&限流未开启时不进行限流及上报

---

.github/workflows/release.yml
.github/workflows/snapshot.yml
codecov.yml

1. SNAPSHOT发布时校验版本号。
2. 仅开启项目级单测覆盖率红线。

feat:update GitHub Action.

---

polaris-configuration/polaris-configuration-client/src/main/java/com/tencent/polaris/configuration/client/util/YamlParser.java

feat:support SnakeYAML 2.0.

---

polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/Connection.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/SpecStreamClient.java

fixes https://github.com/Tencent/spring-cloud-tencent/issues/999

fix:shutdown grpc connection gracefully.

---

polaris-distribution/polaris-all/pom.xml

fix:add okhttp3 shading.

---

polaris-plugins/polaris-plugins-loadbalancer/loadbalancer-ringhash/src/main/java/com/tencent/polaris/plugins/loadbalancer/ringhash/MurmurHash.java

修复JDK低版本Java SDK ByteBuffer.rewind()方法不存在问题

fix rewind bug

---

polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/utils/RuleUtils.java
polaris-common/polaris-model/src/test/java/com/tencent/polaris/api/utils/RuleUtilsTest.java

fix:fix metadata match bug.

---

polaris-configuration/polaris-configuration-client/src/main/java/com/tencent/polaris/configuration/client/internal/RemoteConfigFileRepo.java

Checking executor service status about RemoteConfigFileRepo to prevent pool terminal exception

fix: Checking executor service status about RemoteConfigFileRepo

---

polaris-common/polaris-logging/src/main/java/com/tencent/polaris/logging/logback/LogbackPolarisLogging.java

fix https://github.com/Tencent/spring-cloud-tencent/issues/1099

fix:compatible with higher versions of logback.

---

polaris-common/polaris-config/src/main/java/com/tencent/polaris/api/config/configuration/ConfigFileConfig.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/configuration/ConfigFileConfigImpl.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/configuration/ConfigFilterConfigImpl.java
polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/pom.xml
polaris-plugins/polaris-plugins-configfilefilter/configfilefilter-crypto/src/main/java/com/tencent/polaris/plugins/configfilefilter/CryptoConfigFileFilter.java

fixes https://github.com/polarismesh/polaris/issues/966

fix:optimize crypto config.

---

polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/pojo/HalfOpenStatus.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/CircuitBreakerRuleContainer.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/ResourceCounters.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/test/java/com/tencent/polaris/plugins/circuitbraker/composite/trigger/ResourceCountersTest.java

https://github.com/polarismesh/polaris-java/issues/434

fix: #434 熔断规则被删除后，不再进行状态机的轮转

---

polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java

支持映射nacos命名空间，参考以下：
https://github.com/Tencent/spring-cloud-tencent/issues/737

feat: support setting nacos namespace

---

polaris-plugins/polaris-plugins-connector/connector-nacos/src/main/java/com/tencent/polaris/plugins/connector/nacos/NacosConnector.java

feat: support nacos namespace mapping

---

polaris-configuration/polaris-configuration-api/src/main/java/com/tencent/polaris/configuration/api/rpc/ReleaseConfigFileRequest.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/rpc/WatchInstancesRequest.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultConsumerAPI.java
polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/InMemoryRegistry.java
polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/MessagePersistHandler.java

[ISSUE #455] refactor:优化容灾文件加载逻辑，做成按需加载

---

polaris-plugins/polaris-plugins-registry/registry-memory/src/main/java/com/tencent/polaris/plugins/registry/memory/MessagePersistHandler.java
polaris-plugins/polaris-plugins-registry/registry-memory/src/test/java/com/tencent/polaris/plugins/registry/memory/MessagePersistHandlerTest.java

https://github.com/polarismesh/polaris-java/issues/455

fix: 增加加载缓存文件的保护机制，同一个文件最快只能每10s加载一次缓存文件

---

polaris-common/polaris-config-default/src/main/resources/conf/default-config.yml
polaris-common/polaris-config/src/main/java/com/tencent/polaris/api/config/provider/LosslessConfig.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/api/config/provider/ProviderConfig.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/provider/LosslessConfigImpl.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/config/provider/ProviderConfigImpl.java
polaris-common/polaris-config/src/main/java/com/tencent/polaris/factory/util/ConfigUtils.java
polaris-common/polaris-metadata/pom.xml
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/MetadataContainer.java
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/MetadataManager.java
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/MetadataMapValue.java
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/MetadataStringValue.java
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/MetadataType.java
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/MetadataValue.java
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/TransitiveType.java
polaris-common/polaris-metadata/src/main/java/com/tencent/polaris/metadata/core/impl/MetadataContextImpl.java
polaris-common/pom.xml
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/core/LosslessAPI.java
polaris-discovery/polaris-discovery-api/src/main/java/com/tencent/polaris/api/flow/DiscoveryFlow.java
polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/api/DefaultLosslessAPI.java
polaris-discovery/polaris-discovery-factory/src/main/java/com/tencent/polaris/factory/api/DiscoveryAPIFactory.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/common/PluginTypes.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/lossless/LosslessActionProvider.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/lossless/LosslessPolicy.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/lossless/RegisterStatus.java
polaris-plugins/polaris-plugin-api/src/main/java/com/tencent/polaris/api/plugin/lossless/RegisterStatusProvider.java

feat: new add lossless API 

---

polaris-examples/quickstart-example/README-zh.md
polaris-examples/quickstart-example/README.md

update quickstart README.md

---

polaris-ratelimit/polaris-ratelimit-api/src/main/java/com/tencent/polaris/ratelimit/api/rpc/QuotaResponse.java

https://github.com/polarismesh/polaris-java-agent#183

add getActiveRuleName

---

polaris-circuitbreaker/polaris-circuitbreaker-factory/src/test/java/com/tencent/polaris/circuitbreaker/factory/test/CbTestUtils.java
polaris-circuitbreaker/polaris-circuitbreaker-factory/src/test/java/com/tencent/polaris/circuitbreaker/factory/test/FaultDetectorTest.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/PolarisCircuitBreaker.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/ResourceHealthChecker.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/utils/CircuitBreakerUtils.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/test/java/com/tencent/polaris/plugins/circuitbreaker/composite/PolarisCircuitBreakerTest.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/test/java/com/tencent/polaris/plugins/circuitbreaker/composite/trigger/CircuitBreakerRuleContainerTest.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/test/java/com/tencent/polaris/plugins/circuitbreaker/composite/trigger/ConsecutiveCounterTest.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/test/java/com/tencent/polaris/plugins/circuitbreaker/composite/trigger/ErrRateCounterTest.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/test/java/com/tencent/polaris/plugins/circuitbreaker/composite/trigger/ResourceCountersTest.java
polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/test/java/com/tencent/polaris/plugins/circuitbreaker/composite/trigger/ResourceHealthCheckerTest.java

fix: 优化熔断插件实现，解决用户通配API内存占用过高问题 (#542)

---

polaris-plugins/polaris-plugins-circuitbreaker/circuitbreaker-composite/src/main/java/com/tencent/polaris/plugins/circuitbreaker/composite/PolarisCircuitBreaker.java

fix: use Objects.equals to compare objects.

---

pom.xml

release 2.0.0.0-RC3.

---

pom.xml

release 2.0.0.0-RC4.

---

polaris-plugins/polaris-plugins-observability/event-pushgateway/src/main/java/com/tencent/polaris/plugins/event/pushgateway/PushGatewayEventReporter.java

fix chinese garbled characters in event.

fix: fix chinese garbled characters in event.

---

polaris-plugins/polaris-plugins-connector/connector-consul/src/main/java/com/tencent/polaris/plugins/connector/consul/ConsulAPIConnector.java
polaris-plugins/polaris-plugins-connector/connector-consul/src/main/java/com/tencent/polaris/plugins/connector/consul/ConsulContext.java
polaris-plugins/polaris-plugins-connector/connector-consul/src/main/java/com/tencent/polaris/plugins/connector/consul/service/InstanceService.java
polaris-plugins/polaris-plugins-router/router-nearby/src/main/java/com/tencent/polaris/plugins/router/nearby/NearbyRouter.java

feat:  support empty string zone in nearby router and support changing nsType in consul discovery

feat:  support empty string zone in nearby router and support changing nsType in consul discovery

---

polaris-common/polaris-client/src/main/java/com/tencent/polaris/client/flow/BaseFlow.java

feat: add log if there are no instances after routing

feat: add log if there are no instances after routing

---

polaris-plugins/polaris-plugins-connector/connector-consul/src/main/java/com/tencent/polaris/plugins/connector/consul/service/InstanceService.java

fix: changing the instances status may not affect the index in tsf consul

fix: changing the instances status may not affect the index in tsf consul

---

polaris-common/polaris-model/src/main/java/com/tencent/polaris/api/utils/StringUtils.java
polaris-plugins/polaris-plugins-connector/connector-common/src/main/java/com/tencent/polaris/plugins/connector/common/constant/ConsulConstant.java
polaris-plugins/polaris-plugins-connector/connector-consul/src/main/java/com/tencent/polaris/plugins/connector/consul/ConsulAPIConnector.java
polaris-plugins/polaris-plugins-connector/connector-consul/src/main/java/com/tencent/polaris/plugins/connector/consul/service/InstanceService.java

feat: support TSF unit

---

polaris-discovery/polaris-discovery-client/src/main/java/com/tencent/polaris/discovery/client/flow/RegisterFlow.java

fix: the heartbeat task is changed to use scheduleAtFixedRate.

fix: the heartbeat task is changed to use scheduleAtFixedRate.

---

polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/Connection.java
polaris-plugins/polaris-plugins-connector/connector-polaris-grpc/src/main/java/com/tencent/polaris/plugins/connector/grpc/GrpcConnector.java

fix: use ReentrantLock instead of synchronized in Connection.

fix: use ReentrantLock instead of synchronized in Connection.
